### ISSUE TITLE
Task Creation

### ISSUE THREAD

**Issue by jCabreraAltimetrik** [altimetrik-onboarding-uy/jmcabrera#1]
As a Sys. Admin i want a way to keep track of assigned duties to users
so that i better know who is working on what.

[TaskCreationDevNotes.txt](https://github.com/altimetrik-onboarding-uy/jmcabrera/files/3983532/TaskCreationDevNotes.txt)

**Comment by stefaniaoverman** [comment]
good

**Comment by jCabreraAltimetrik** [comment]
Added name and description field to task.
