### ISSUE TITLE
App Available for contacts

### ISSUE THREAD

**Issue by jCabreraAltimetrik** [altimetrik-onboarding-uy/jmcabrera#13]
As an admin i would like to give all contacts the ability to check on their tasks
in an easy to acces app so they can seize their time.

**Comment by stefaniaoverman** [comment]
Might be better: As an admin i would like to give all contacts the ability to check on their tasks
in an easy to access app **so they can seize their time.**

**Comment by jCabreraAltimetrik** [comment]
Modified story as required. 
Enabled an aura component as a tab for easy usage. Can be used on contact detail page.
