### ISSUE TITLE
Task display

### ISSUE THREAD

**Issue by jCabreraAltimetrik** [altimetrik-onboarding-uy/jmcabrera#15]
As an admin i need the to-do and daily task  to be displayed until they have been completed;
on the other hand, habit task must remain listed until deleted in order to have better control over periodical events.

**Comment by stefaniaoverman** [comment]
As an admin i need the to-do and daily task to be displayed until they have been completed;
on the other hand, habit task must remain listed until deleted **in order to** have better control over periodical events.

**Comment by jCabreraAltimetrik** [comment]
Modified story as required.
Modified aura component controller to allow for task to be displayed as required.
