### ISSUE TITLE
Task completion

### ISSUE THREAD

**Issue by jCabreraAltimetrik** [altimetrik-onboarding-uy/jmcabrera#16]
As an admin i would need to give contacts the ability to complete habit task either
with a success or a failure, points being calculated based on the resulting state of the task, so contacts have better control over their task completion and have instant notification of their current points.

**Comment by stefaniaoverman** [comment]
so they can be able of.....??

**Comment by jCabreraAltimetrik** [comment]
Added missing data to story.
Added complete and failure  buttons to task users as required
