### ISSUE TITLE
Task Status

### ISSUE THREAD

**Issue by jCabreraAltimetrik** [altimetrik-onboarding-uy/jmcabrera#3]
As a Sys. admin i need a way for users to manage the progress of their assigned task
so we can be informed on its status when it comes to non-daily tasks

[TaskStatusDevNotes.txt](https://github.com/altimetrik-onboarding-uy/jmcabrera/files/3983540/TaskStatusDevNotes.txt)

**Comment by stefaniaoverman** [comment]
Maybe would be better: As a Sys. admin I need the users to be able to manage the progress of their assigned task so we can be informed on its status when it comes to non-daily tasks

**Comment by jCabreraAltimetrik** [comment]
Modified story as per required; Added new, in progress,completed to status picklist
